from django.test import TestCase
from content.images import style_transcript_image

class StyleTranscriptImageTest(TestCase):

    def test_style_transcript_image(self):
        input_html = """
        <p>As she began to unravel the web of the Spanish Forger, Belle da Costa Greene was pulling off a successful masquerade of her own. Greene was in fact born Belle Greener, daughter of African American parents of mixed heritage. Her father was Theodore Greener &mdash; the first African American graduate of Harvard. At some point in her early adulthood, Belle changed her name from &ldquo;Greener&rdquo; to &ldquo;da Costa Greene,&rdquo; and invented a Portuguese grandmother to explain her dark complexion. It was the beginning of her new life as a white person. She trained as a teacher and then a librarian, getting a job at Princeton University Library. It&rsquo;s a testament to Greene&rsquo;s courage that she achieved this: in the 1930s an alumnus of Princeton wrote from his home in Missouri to the college&rsquo;s president, enthusiastically telling him that &ldquo;one of the reasons Princeton is so popular here is that it is the one Eastern school that does not enroll negroes.&rdquo;</p>
        <figure class="figure_transcript_double"><a class="fancybox_transcript" href="/media/uploads/2017/12/05/tr_muslim_veil_zohra_drif.jpg" title="An image"><img alt="" class="tr_image_double" longdesc="double" src="/media/uploads/2017/12/05/tr_muslim_veil_zohra_drif.jpg" /></a>
        <figcaption>An image</figcaption>
        </figure>
        <figure class="figure_transcript_double"><a class="fancybox_transcript" href="/media/uploads/2017/12/21/tr_image_spanish_forger1.jpg" title="A caption!"><img alt="" class="tr_image_double" longdesc="double" src="/media/uploads/2017/12/21/tr_image_spanish_forger1.jpg" style="" title="A caption!" /></a>
        <figcaption>A caption!</figcaption>
        </figure>
        <p>&nbsp;</p>
        <p>While she was working at Princeton, she met student Junius Spencer Morgan II, who introduced her to his uncle, John Pierpont Morgan, more commonly known as J.P. Morgan. Morgan hired Greene in 1905 to be his chief librarian, and she would hold this job for 43 years, later becoming director of the Morgan Library. In 1921, the&nbsp;<i>Chicago Daily Tribune</i>&nbsp;ran a profile of Greene, in which it said: &ldquo;she wears her hair long and does not wear glasses, runs to Europe on secret missions and is the terror of Continental collector&rsquo;s agents.&rdquo;</p>
        """
        expected_html = """\n<p>As she began to unravel the web of the Spanish Forger, Belle da Costa Greene was pulling off a successful masquerade of her own. Greene was in fact born Belle Greener, daughter of African American parents of mixed heritage. Her father was Theodore Greener — the first African American graduate of Harvard. At some point in her early adulthood, Belle changed her name from “Greener” to “da Costa Greene,” and invented a Portuguese grandmother to explain her dark complexion. It was the beginning of her new life as a white person. She trained as a teacher and then a librarian, getting a job at Princeton University Library. It’s a testament to Greene’s courage that she achieved this: in the 1930s an alumnus of Princeton wrote from his home in Missouri to the college’s president, enthusiastically telling him that “one of the reasons Princeton is so popular here is that it is the one Eastern school that does not enroll negroes.”</p>\n<div class="row"><div class="col-md-6"><figure class="figure_transcript_double"><a class="fancybox_transcript" href="/media/uploads/2017/12/05/tr_muslim_veil_zohra_drif.jpg" title="An image"><img alt="" class="tr_image_double" longdesc="double" src="/media/uploads/2017/12/05/tr_muslim_veil_zohra_drif.jpg"/></a>\n<figcaption>An image</figcaption>\n</figure></div><div class="col-md-6"><figure class="figure_transcript_double"><a class="fancybox_transcript" href="/media/uploads/2017/12/21/tr_image_spanish_forger1.jpg" title="A caption!"><img alt="" class="tr_image_double" longdesc="double" src="/media/uploads/2017/12/21/tr_image_spanish_forger1.jpg" style="" title="A caption!"/></a>\n<figcaption>A caption!</figcaption>\n</figure></div></div>\n\n<p>\xa0</p>\n<p>While she was working at Princeton, she met student Junius Spencer Morgan II, who introduced her to his uncle, John Pierpont Morgan, more commonly known as J.P. Morgan. Morgan hired Greene in 1905 to be his chief librarian, and she would hold this job for 43 years, later becoming director of the Morgan Library. In 1921, the\xa0<i>Chicago Daily Tribune</i>\xa0ran a profile of Greene, in which it said: “she wears her hair long and does not wear glasses, runs to Europe on secret missions and is the terror of Continental collector’s agents.”</p>\n"""
        
        html_dict = {input_html: expected_html}
        for in_html, exp_html in html_dict.items():
            self.assertEqual(exp_html, style_transcript_image(in_html))
