# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 21:15
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='le author name', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bio', ckeditor.fields.RichTextField(default='author bio')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(default='le discipline', help_text='topic discipline (ex: Neuroscience)', max_length=100)),
                ('academic_field', models.CharField(choices=[('S', 'Sciences'), ('H', 'Humanities')], help_text='Sciences or Humanities', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('title', models.CharField(default='le title', max_length=100, unique=True)),
                ('topic_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cover image')),
                ('topic_image_latest', models.ImageField(blank=True, help_text="The cover image for 'featured' on the homepage", null=True, upload_to='', verbose_name="'featured episode' cover image")),
                ('topic_image_box', models.ImageField(blank=True, help_text='This is for the circular audio player on mobile', null=True, upload_to='', verbose_name='Mobile circular image')),
                ('transcript', ckeditor_uploader.fields.RichTextUploadingField(default='le transcript')),
                ('abstract', ckeditor.fields.RichTextField(default='le abstract')),
                ('by_in_colour', models.CharField(choices=[('w', 'white'), ('b', 'black')], default='b', max_length=1, verbose_name="'by/in' colour")),
                ('author_name_size', models.CharField(choices=[('n', 'normal'), ('s', 'smaller')], default='n', max_length=1)),
                ('image_credits', ckeditor.fields.RichTextField(blank=True, default="correct format: The Morgan Library & Museum, New York. By <a target='_blank' href='https://commons.wikimedia.org/wiki/File:The_Morgan_Library_%26_Museum.jpg'>Paolatrabanco</a> [<a target='_blank' href='https://creativecommons.org/licenses/by-sa/4.0/deed.en'>CC BY-SA 4.0</a>]")),
                ('narration_credits', models.CharField(blank=True, default='correct format: Mary Wellesley and Vidish Athavale', max_length=300)),
                ('music_credits', models.CharField(blank=True, default='correct format: Greg Joy and Neil Cross', max_length=300)),
                ('video_embed', models.CharField(blank=True, default='', max_length=300, verbose_name='Youtube URL')),
                ('audio_mp3', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('v', 'Previewed')], default='d', max_length=1)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Author')),
                ('classification', models.ManyToManyField(blank=True, to='content.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='FlashSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='le title', max_length=100, unique=True)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_location', models.CharField(default='somewhere', max_length=400)),
                ('description', ckeditor.fields.RichTextField(default='a flash seminar!')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('v', 'Previewed')], default='d', max_length=1)),
                ('slug', models.SlugField(default='le slug', max_length=120, unique=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Episode')),
            ],
        ),
    ]
