# Generated by Django 2.0.1 on 2018-08-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='general_credits',
            field=models.CharField(blank=True, default='', help_text="Name of podcast interviewer. Example format: 'interviewed by Ellen O'Neill'", max_length=300),
        ),
    ]
