# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-24 22:51
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='old_KiW_slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image_credits',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text="Example of the correct format: The Morgan Library & Museum, New York. By <a target='_blank' href='https://commons.wikimedia.org/wiki/File:The_Morgan_Library_%26_Museum.jpg'>Paolatrabanco</a> [<a target='_blank' href='https://creativecommons.org/licenses/by-sa/4.0/deed.en'>CC BY-SA 4.0</a>]"),
        ),
        migrations.AlterField(
            model_name='episode',
            name='music_credits',
            field=models.CharField(blank=True, default='', help_text='Example of correct format: Greg Joy and Neil Cross', max_length=300),
        ),
        migrations.AlterField(
            model_name='episode',
            name='narration_credits',
            field=models.CharField(blank=True, default='', help_text='Example of correct format: Mary Wellesley and Vidish Athavale', max_length=300),
        ),
    ]
