# Generated by Django 2.0.1 on 2018-08-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180105_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='second_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_author', to='content.Author'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='content.Author'),
        ),
    ]
