# Generated by Django 2.0.1 on 2018-06-07 18:29

import ckeditor.fields
import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180105_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Season title', max_length=100)),
                ('abstract', ckeditor.fields.RichTextField(default='Description of the season')),
                ('image', models.ImageField(blank=True, null=True, upload_to=content.models.seasons_image_directory_path, verbose_name='Season image')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Season'),
        ),
    ]
