# Generated by Django 2.0.1 on 2018-07-03 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180607_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
