# Generated by Django 2.0.1 on 2018-08-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180806_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='second_author',
            field=models.ForeignKey(blank=True, help_text='A second author is optional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_author', to='content.Author'),
        ),
    ]
