# Generated by Django 2.0.1 on 2018-08-27 09:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180806_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='transcript',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='le transcript', null=True),
        ),
    ]
