# Generated by Django 2.0.1 on 2018-08-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_season_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='second_author',
            field=models.ForeignKey(blank=True, help_text='A second author is optional', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_author', to='content.Author'),
        ),
    ]
