# Generated by Django 2.0.1 on 2018-08-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20180827_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_author', to='content.Author'),
        ),
    ]
